name: animated_dialog
description: A simple Animated Dialog, with editable content, maintain organization, class and design with animated dialogs for bringing live to your app.
version: 1.0.3
homepage: https://github.com/djcharles26/
repository: https://github.com/Djcharles26/animated_dialog.git

license: ISC

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
